name: MiniWDL linter CI Dev DockerFile

on:
  push:
  workflow_dispatch:

jobs:
  run-miniwdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # specify the Python version you need

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER

    - name: Build Docker Image
      run: |
        docker build -t local-metams:latest .

    - name: Install MiniWDL
      run: |
        python -m pip install --upgrade pip
        pip install miniwdl

    - name: Run MiniWDL
      run: |
        miniwdl run wdl/metaMS_lipidomics.wdl -i wdl/metams_input_lipidomics.json --verbose --no-cache --copy-input-files